In [1]:
from transformers import AutoTokenizer,AutoModelForSequenceClassification

In [4]:
test_sentence = ["today is not that bad","today is so bad"]
model_name = 'distilbert-base-uncased-finetuned-sst-2-english'

In [5]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [8]:
batch_input = tokenizer(test_sentence,truncation=True,padding=True,return_tensors='pt')

In [9]:
batch_input

{'input_ids': tensor([[ 101, 2651, 2003, 2025, 2008, 2919,  102],
        [ 101, 2651, 2003, 2061, 2919,  102,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0]])}

In [10]:
tokenizer(test_sentence[0],)

{'input_ids': [101, 2651, 2003, 2025, 2008, 2919, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

In [11]:
tokenizer.encode(test_sentence[0],)

[101, 2651, 2003, 2025, 2008, 2919, 102]

In [13]:
token = tokenizer.tokenize(test_sentence[0])

In [14]:
tokenizer.convert_tokens_to_ids(token)

[2651, 2003, 2025, 2008, 2919]

In [15]:
tokenizer.decode([101, 2651, 2003, 2025, 2008, 2919,  102])

'[CLS] today is not that bad [SEP]'

In [16]:
tokenizer.vocab

{'##lster': 29576,
 'ngos': 22165,
 'breadth': 25291,
 '##zily': 28431,
 '،': 1268,
 'motifs': 17366,
 'bay': 3016,
 'belarus': 12545,
 '小': 1829,
 'cougars': 26317,
 'gesture': 9218,
 'blew': 8682,
 'ezra': 16245,
 'substantially': 12381,
 'racist': 16939,
 'soothing': 16684,
 '56th': 29087,
 'ecology': 13517,
 '[unused595]': 600,
 'tak': 27006,
 '##uating': 24133,
 'mcgregor': 23023,
 'localized': 22574,
 'ʸ': 1144,
 'questionable': 21068,
 'bananas': 26191,
 'dictator': 21237,
 'composer': 4543,
 '##ナ': 30241,
 'plaintiff': 20579,
 'irony': 19728,
 '春': 1867,
 'badge': 10780,
 '[unused460]': 465,
 '##cave': 27454,
 'novo': 24576,
 '[unused759]': 764,
 '##mark': 10665,
 '##unt': 16671,
 'prophet': 12168,
 'australian': 2827,
 'castle': 3317,
 '[unused14]': 15,
 'drawn': 4567,
 '##raction': 25533,
 '##iciencies': 28227,
 'constellation': 15300,
 'intentionally': 15734,
 'photographers': 17008,
 'ford': 4811,
 'determine': 5646,
 'transferring': 14391,
 '1624': 28531,
 'დ': 1441,
 'lib

In [17]:
import torch
import torch.nn.functional as F

In [22]:
with torch.no_grad():
  outputs = model(**batch_input)
  print(outputs)
  print(outputs.logits)
  scores = F.softmax(outputs.logits,dim=1)
  print(scores)
  labels = torch.argmax(scores,dim=1)
  print(labels)
  labels = [model.config.id2label[id] for id in labels.tolist()]
  print(labels)

SequenceClassifierOutput(loss=None, logits=tensor([[-3.4620,  3.6118],
        [ 4.7508, -3.7899]]), hidden_states=None, attentions=None)
tensor([[-3.4620,  3.6118],
        [ 4.7508, -3.7899]])
tensor([[8.4632e-04, 9.9915e-01],
        [9.9980e-01, 1.9531e-04]])
tensor([1, 0])
['POSITIVE', 'NEGATIVE']
